name: Fist PR Greeting

on: [pull_request]

jobs: 
  greeting:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps: 
    - uses: actions/first-interaction@v1
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thanks for the PR, I'll review and post feedback if any is needed.'
